// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayiluypvbpxhbuwthokx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5aWx1eXB2YnB4aGJ1d3Rob2t4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MzIwOTYsImV4cCI6MjA2NzQwODA5Nn0.QWEVv1vGIOjSkpeZ16m3LvR2_EnqHD2c-Nmq-K_aLAU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});